create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  visitor_id uuid not null,
  session_id uuid not null,
  event_type text not null check (event_type in ('page_view', 'share')),
  content_type text not null default 'site' check (content_type in ('site', 'column', 'notice', 'replay', 'gpt', 'app', 'schedule')),
  content_id text,
  path text not null check (path like '/%' and char_length(path) <= 500),
  referrer_host text check (referrer_host is null or char_length(referrer_host) <= 255),
  share_channel text check (share_channel is null or share_channel in ('native', 'copy', 'naver', 'facebook', 'x')),
  device_type text not null default 'unknown' check (device_type in ('desktop', 'tablet', 'mobile', 'unknown')),
  utm_source text check (utm_source is null or char_length(utm_source) <= 120),
  utm_medium text check (utm_medium is null or char_length(utm_medium) <= 120),
  utm_campaign text check (utm_campaign is null or char_length(utm_campaign) <= 120),
  event_date date not null default ((now() at time zone 'utc')::date),
  event_bucket timestamptz not null default date_trunc('minute', now()),
  created_at timestamptz not null default now(),
  constraint analytics_share_channel_check check (
    (event_type = 'page_view' and share_channel is null)
    or (event_type = 'share' and share_channel is not null)
  )
);

create index if not exists analytics_events_created_at_idx
  on public.analytics_events (created_at desc);
create index if not exists analytics_events_event_date_idx
  on public.analytics_events (event_type, event_date desc);
create index if not exists analytics_events_content_idx
  on public.analytics_events (content_type, content_id, event_date desc);
create index if not exists analytics_events_path_idx
  on public.analytics_events (path, event_date desc);
create unique index if not exists analytics_events_page_view_minute_key
  on public.analytics_events (visitor_id, path, event_bucket)
  where event_type = 'page_view';
create unique index if not exists analytics_events_share_minute_key
  on public.analytics_events (visitor_id, path, share_channel, event_bucket)
  where event_type = 'share';

alter table public.analytics_events enable row level security;

revoke all on table public.analytics_events from anon, authenticated;
grant insert on table public.analytics_events to anon, authenticated;
grant select on table public.analytics_events to authenticated;
grant usage, select on sequence public.analytics_events_id_seq to anon, authenticated;

drop policy if exists "Public may record analytics events" on public.analytics_events;
create policy "Public may record analytics events"
on public.analytics_events
for insert
to anon, authenticated
with check (
  path not like '/admin%'
  and path not like '/login%'
  and char_length(path) between 1 and 500
);

drop policy if exists "Admins may read analytics events" on public.analytics_events;
create policy "Admins may read analytics events"
on public.analytics_events
for select
to authenticated
using (((select auth.jwt()) -> 'app_metadata' ->> 'role') = 'admin');

create or replace view public.analytics_overview
with (security_invoker = true)
as
select
  count(*) filter (where event_type = 'page_view')::bigint as total_page_views,
  count(distinct visitor_id) filter (where event_type = 'page_view')::bigint as total_unique_visitors,
  count(*) filter (where event_type = 'page_view' and created_at >= now() - interval '30 days')::bigint as last_30d_page_views,
  count(distinct visitor_id) filter (where event_type = 'page_view' and created_at >= now() - interval '30 days')::bigint as last_30d_unique_visitors,
  count(*) filter (where event_type = 'page_view' and event_date = (now() at time zone 'utc')::date)::bigint as today_page_views,
  count(distinct visitor_id) filter (where event_type = 'page_view' and event_date = (now() at time zone 'utc')::date)::bigint as today_unique_visitors,
  count(*) filter (where event_type = 'share')::bigint as total_shares,
  count(*) filter (where event_type = 'share' and created_at >= now() - interval '30 days')::bigint as last_30d_shares
from public.analytics_events;

create or replace view public.analytics_daily_summary
with (security_invoker = true)
as
select
  event_date,
  count(*) filter (where event_type = 'page_view')::bigint as page_views,
  count(distinct visitor_id) filter (where event_type = 'page_view')::bigint as unique_visitors,
  count(*) filter (where event_type = 'share')::bigint as shares
from public.analytics_events
group by event_date;

create or replace view public.analytics_page_summary
with (security_invoker = true)
as
select
  path,
  content_type,
  content_id,
  count(*) filter (where event_type = 'page_view')::bigint as page_views,
  count(distinct visitor_id) filter (where event_type = 'page_view')::bigint as unique_visitors,
  count(*) filter (where event_type = 'share')::bigint as shares,
  max(created_at) as last_activity_at
from public.analytics_events
group by path, content_type, content_id;

create or replace view public.analytics_content_summary
with (security_invoker = true)
as
select
  e.content_type,
  e.content_id,
  e.path,
  coalesce(max(c.title), e.path) as title,
  count(*) filter (where e.event_type = 'page_view')::bigint as page_views,
  count(distinct e.visitor_id) filter (where e.event_type = 'page_view')::bigint as unique_visitors,
  count(*) filter (where e.event_type = 'share')::bigint as shares,
  max(e.created_at) as last_activity_at
from public.analytics_events e
left join public.contents c
  on c.id = e.content_id
  and c.kind = e.content_type
where e.content_id is not null
group by e.content_type, e.content_id, e.path;

revoke all on table public.analytics_overview from anon, authenticated;
revoke all on table public.analytics_daily_summary from anon, authenticated;
revoke all on table public.analytics_page_summary from anon, authenticated;
revoke all on table public.analytics_content_summary from anon, authenticated;
grant select on table public.analytics_overview to authenticated;
grant select on table public.analytics_daily_summary to authenticated;
grant select on table public.analytics_page_summary to authenticated;
grant select on table public.analytics_content_summary to authenticated;

comment on table public.analytics_events is
  'Privacy-conscious first-party analytics. Stores browser-generated IDs and page activity, not raw IP addresses.';
